services:
  - type: web
    name: todoapp-backend
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node backend/app.js'
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000